version: '3'

services:
  ec-cube:
    environment:
      USER_ID: ${UID:-}
      GROUP_ID: ${GID:-}
    volumes:
      - ".:/var/www/html:cached"
      ### 同期対象からコストの重いフォルダを除外 #####################
      - "var:/var/www/html/var"
      - "vendor:/var/www/html/vendor"
      - "node_modules:/var/www/html/node_modules"      
