monolog:
    handlers:
        buffered:
            type:     buffer
            handler:  easylog
            channels: ["!event"]
            level:    debug
        easylog:
            type: service
            id:   easycorp.easylog.handler
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        main:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: main_rotating_file
        main_rotating_file:
            type: rotating_file
            max_files: 60
            path: '%kernel.logs_dir%/%kernel.environment%/debug.log'
            formatter: eccube.log.formatter.line
            level: debug
        warning:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: warning_rotating_file
        warning_rotating_file:
            type: rotating_file
            max_files: 60
            path: '%kernel.logs_dir%/%kernel.environment%/warning.log'
            formatter: eccube.log.formatter.line
            level: warning
services:
    easycorp.easylog.handler:
        class: EasyCorp\EasyLog\EasyLogHandler
        public: false
        arguments:
            - '%kernel.logs_dir%/%kernel.environment%/site.log'
